- name: cart module
  hosts: cart
  become: yes
  tasks:

  - name: disabling nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: instlling nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Create a directory 
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
    ansible.builtin.user:
      name: roboshop
      shell: /bin/nologin
      system : yes
      home: /app
      
  - name: downloading app
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip 

  - name: unzipping app
    ansible.builtin.unarchive:
      src: /tmp/cart.zip 
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copying cart.service to node
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service  

  - name: Reload service user
    ansible.builtin.systemd_service:
       daemon_reload: true

  - name: start and enable cart.service
    ansible.builtin.service:
      name: cart.service
      state: started
      enabled: yes