- name: catalogue configration
  hosts: catalogue
  become: yes
  tasks:
  - name: disabling nodejs
    ansible.builtin.command: dnf module disable nodejs -y
     
  - name: enabling nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
    
  - name: installing nodejs 20
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: cereating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Creating roboshop system user
    ansible.builtin.user:
      name: roboshop
      home : /app
      system: yes
      shell: /sbin/nologin

  - name: downloading application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: uzipping the project 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install packages based on package.json.
    community.general.npm:
      path: /app

  - name: copying catalogue.service to catalogue nodejs
    ansible.builtin.copy:
      src: catalogue.service
      dest: "/etc/systemd/system/catalogue.service"

  - name: Reload 
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: copying mongodb
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: instlling mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0




  