- name: catalogue configration
  hosts: catalogue
  tasks:
  - name: disabling nodejs
    anasible.builtin.commad: dnf disable nodejs -y
     
  - name: enabling nodejs
    ansible.buildin.commans: dnf module enable nodejs:20 -y
    
  - name: installing nodejs 20
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: cereating app directory
    ansible.builtin.file:
    path: /app
    state: directory

  - name: Creating roboshop system user
    ansible.builtin.user:
      name: roboshop
      home : /app
      system: yes
      shell: /sbin/nologin