- name: frontend module
  hosts: frontend
  become: yes
  tasks:
  
  - name: disbaling nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enabling nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.package:
      name: ngnix
      state: started
      enabled: yes
  
  - name: installing frontend content
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: removing the content from index.html
    ansible.builtin.file:
      path: "/usr/share/nginx/html/*" 
      state: absent

  - name: removing the content from index.html
    ansible.builtin.file:
      path: "/usr/share/nginx/html"
      state: directory

  - name: unzipping the content of html
    ansible.builtin.unarchive:
      src: "/tmp/frontend.zip"
      dest: "/usr/share/nginx/html"
      remote_src: yes

  - name: copying nginx.conf to server
    ansible.builtin.copy:
      src: "nginx.conf"
      dest: "/etc/nginx/nginx.conf"


  - name: system restart
    ansible.builtin.service:
      name: frontend
      state: started
