- name: user module
  hosts: user
  become: yes
  tasks: 
  - name: disable nodejs
    ansible.builtin,command: dnf module disable nodejs -y

  - name: enable module nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -yaml

  - name: install node js
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creating system user
    ansible.builtin.user:
      name: roboshop
      shell: /bin/nologin
      system: yes
      home: /app
    
  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: director
  
  - name: downloading app
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
    
  - name: unzipping the app
    ansible.builtin.archive:
      scr: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: installing dependincies
    community.general.npm:
        path: /app

  - name: copying services to app folder
    ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/user.service

  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: system start and enable
    ansible.builtin.service:
      name: user
      state: started
      enable: yes
    